./fujii.py C1.tbl > C1.json
./fujii.py C2.tbl > C2.json
./fujii.py C3.tbl > C3.json
./fujii.py C4.tbl > C4.json
./fujii.py C5.tbl > C5.json
./fujii.py Ca1.tbl > Ca1.json
./fujii.py Ca2.tbl > Ca2.json
./fujii.py Ca3.tbl > Ca3.json
./fujii.py Ca4.tbl > Ca4.json
./fujii.py Ca5.tbl > Ca5.json
./fujii.py D1.tbl > D1.json
./fujii.py D2.tbl > D2.json
./fujii.py D3.tbl > D3.json
./fujii.py D4.tbl > D4.json
./fujii.py D5.tbl > D5.json
./fujii.py Li1.tbl > Li1.json
./fujii.py Li2.tbl > Li2.json
./fujii.py Li3.tbl > Li3.json
./fujii.py Li4.tbl > Li4.json
./fujii.py Li5.tbl > Li5.json
./fujii.py Pb1.tbl > Pb1.json
./fujii.py Pb2.tbl > Pb2.json
./fujii.py Pb3.tbl > Pb3.json
./fujii.py Pb4.tbl > Pb4.json
./fujii.py Pb5.tbl > Pb5.json
./fujii.py Zr1.tbl > Zr1.json
./fujii.py Zr2.tbl > Zr2.json
./fujii.py Zr3.tbl > Zr3.json
./fujii.py Zr4.tbl > Zr4.json
./fujii.py Zr5.tbl > Zr5.json
